apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-ai-agent-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: ai-agent.125.6.40.43.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-ai-agent
            port:
              number: 80
