apiVersion: v1
kind: Secret
metadata:
  name: k8s-ai-agent-secrets
  namespace: default
type: Opaque
data:
  OPENAI_API_KEY: "eW91ci1vcGVuYWktYXBpLWtleQ=="
  NEO4J_PASSWORD: "cGFzc3dvcmQ="  # password
